services:
  - type: web
    name: hnql
    runtime: node
    plan: free
    buildCommand: yarn install; yarn build
    startCommand: node ./dist/index.js
    autoDeploy: true
    envVars:
      - key: SERVICE_ENV
        value: production
g